[package]
name = "stablediffusion"
version = "0.2.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
wgpu-backend = ["burn/wgpu"]
rocm-backend = ["burn/rocm"]
torch-backend = ["burn/tch"]

[dependencies]
### For local development. ###
#burn = { path="../burn/crates/burn", default-features = false, features=["std"] }
#burn-ndarray = {path="../burn/crates/burn-ndarray" }
#burn-autodiff = { path="../burn/crates/burn-autodiff" }
#burn-tch = {path="../burn/crates/burn-tch"}
##burn-import = {path="../burn/crates/burn-import"}

burn = { version = "0.21.0", default-features = false, features=["std", "ndarray", "autodiff", "store"] }
burn-store = { version = "0.21.0", features = ["std", "burnpack"] }
#torch
#tch = { version= "0.22.0", optional = true }

serde = {version = "1.0.228", features = ["std", "derive"]}
num-traits = "0.2.15"
rust_tokenizers = "8.1.0"
regex = "1.12.1"
image = {version="0.25.9", default-features=false, features=["png"]}
cfg-if = "0.1"
